image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.10.2
replicas: 1
resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"
podAnnotations:
  co.elastic.logs/disable: "true"
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
securityContext:
  runAsUser: 1000
service:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: inter-node
      port: 9300
      targetPort: 9300
      protocol: TCP
env:
  - name: "discovery.type"
    value: "single-node"
